//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeidaStudy.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeidaStudy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _1428235353692 {
            get {
                object obj = ResourceManager.GetObject("_1428235353692", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 all,2015春-网络教学综合平台在线总时长----总时长无加速功能
        ///10043,2015春-[网络课]ACCESS2000中文版入门与提高 柏晓辉
        ///17454,2015春-[网络课]C++语言基础教程 杨国燕
        ///17449,2015春-[网络课]JAVA 2实用教程 毕德刚
        ///17455,2015春-[网络课]JSP实用教程 潘晓鸥
        ///10072,2015春-[网络课]边用边学 3DS MAX 5.0 于锁利
        ///10073,2015春-[网络课]边用边学AUTHORWARE6多媒体制作实例详解 孙柏祥
        ///10076,2015春-[网络课]边用边学JAVASCRIPT 张涛
        ///10077,2015春-[网络课]边用边学多媒体教学课件制作 张涛
        ///15176,2015春-[网络课]餐饮盈利技巧 王振
        ///17450,2015春-[网络课]常用工具软件(常用工具软件Ⅰ) 吴华洋
        ///15179,2015春-[网络课]大学生的形象构成设计 张瑞生
        ///15177,2015春-[网络课]导游技巧与艺术 王振
        ///17452,2015春-[网络课]电子商务基础 任春玉
        ///17451,2015春-[网络课]电子商务实务 任 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string course {
            get {
                return ResourceManager.GetString("course", resourceCulture);
            }
        }
    }
}
