//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeidaStudy.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeidaStudy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _1428235353692 {
            get {
                object obj = ResourceManager.GetObject("_1428235353692", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 all,2015秋-网络教学综合平台在线总时长----总时长无加速功能
        ///35729,2015秋-[网络课]Photoshop创新图像设计实用教程 李俊才
        ///36390,2015秋-[网络课]大学生心理自助与成长 朱秋鹰
        ///36391,2015秋-[网络课]ASP.NetWeb实用开发技术 吴华洋
        ///36392,2015秋-[网络课]边用边学Authorware6多媒体制作实例详 孙柏祥
        ///36393,2015秋-[网络课]边用边学JavaScript 张涛
        ///36394,2015秋-[网络课]AJAX实用开发技术 李秋源
        ///36395,2015秋-[网络课]常用工具软件III 吴华洋
        ///36396,2015秋-[网络课]边用边学Fireworks8 田瑜辉
        ///36397,2015秋-[网络课]边用边学Authorware多媒体与课件制作 张涛
        ///36398,2015秋-[网络课]边用边学PHP网站开发 李秋源
        ///27567,形势任务教育(上) 王巍巍
        ///27568,形势任务教育(下) 沈莉华
        ///27569,形势任务教育(下) 张郁慧
        ///31863,形势任务教育(下) 王巍巍
        ///31864,形势任务教育(下) [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string course {
            get {
                return ResourceManager.GetString("course", resourceCulture);
            }
        }
    }
}
